server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/beitaoi/spirngcloud
          username: 360616002@qq.com
          password: zhang971500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/