console.log(true && true);
console.log(1 && true);
console.log(1 && 2);
console.log("A" && 2);
console.log("" && 2);
console.log(null && "B");
console.log("A" && "B");
console.log(1 && 2 && 3);
console.log(1 && null && 3);
console.log("" && null && 0);
console.log(true || true);
console.log(1 || true);
console.log(1 || 2);
console.log("A" || 2);
console.log("" || 2);
console.log(null || "B");
console.log("A" || "B");
console.log(1 || 2 || 3);
console.log(1 || null || 3);
console.log("" || null || 0);