server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wuhengyu/luowowo-springcloud
          username: 15048348071@163.com
          password: why694091282
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/